<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jenjang extends MY_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Jenjang_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template('content/jenjang/jenjang');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Jenjang_model->json();
    }

    public function read($id) 
    {
        $row = $this->Jenjang_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_jenjang' => $row->id_jenjang,
		'jenjang' => $row->jenjang,
	    );
            $this->template('jenjang/tbl_jenjang_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jenjang'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('jenjang/create_action'),
	    'id_jenjang' => set_value('id_jenjang'),
	    'jenjang' => set_value('jenjang'),
	);
        $this->template('jenjang/tbl_jenjang_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'jenjang' => $this->input->post('jenjang',TRUE),
	    );

            $this->Jenjang_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('jenjang'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Jenjang_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('jenjang/update_action'),
		'id_jenjang' => set_value('id_jenjang', $row->id_jenjang),
		'jenjang' => set_value('jenjang', $row->jenjang),
	    );
            $this->template('jenjang/tbl_jenjang_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jenjang'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_jenjang', TRUE));
        } else {
            $data = array(
		'jenjang' => $this->input->post('jenjang',TRUE),
	    );

            $this->Jenjang_model->update($this->input->post('id_jenjang', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('jenjang'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Jenjang_model->get_by_id($id);

        if ($row) {
            $this->Jenjang_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('jenjang'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jenjang'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('jenjang', 'jenjang', 'trim|required');

	$this->form_validation->set_rules('id_jenjang', 'id_jenjang', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Jenjang.php */
/* Location: ./application/controllers/Jenjang.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-05-08 16:16:14 */
/* http://harviacode.com */