<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sekolah extends MY_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sekolah_model');
    }

    public function index()
    {
        $x['sekolah'] = $this->Sekolah_model->get_all();
        $this->template('content/sekolah/sekolah_list',$x);
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Sekolah_model->json();
    }

    public function read($id) 
    {
        $row = $this->Sekolah_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_sekolah' => $row->id_sekolah,
		'nama_sekolah' => $row->nama_sekolah,
	    );
            $this->load->view('sekolah/tbl_sekolah_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('sekolah'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('sekolah/create_action'),
	    'id_sekolah' => set_value('id_sekolah'),
	    'nama_sekolah' => set_value('nama_sekolah'),
	);
        $this->load->view('sekolah/tbl_sekolah_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_sekolah' => $this->input->post('nama_sekolah',TRUE),
	    );

            $this->Sekolah_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect('sekolah');
        }
    }
    
    public function update($id) 
    {
        $row = $this->Sekolah_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('sekolah/update_action'),
		'id_sekolah' => set_value('id_sekolah', $row->id_sekolah),
		'nama_sekolah' => set_value('nama_sekolah', $row->nama_sekolah),
	    );
            $this->load->view('sekolah/tbl_sekolah_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect('sekolah');
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_sekolah', TRUE));
        } else {
            $data = array(
		'nama_sekolah' => $this->input->post('nama_sekolah',TRUE),
	    );

            $this->Sekolah_model->update($this->input->post('id_sekolah', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect('sekolah');
        }
    }
    
    public function delete_action() 
    {
        $id = $this->input->post('id_sekolah');
        $row = $this->Sekolah_model->get_by_id($id);

        if ($row) {
            $this->Sekolah_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect('sekolah');
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect('sekolah');
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_sekolah', 'nama sekolah', 'trim|required');

	$this->form_validation->set_rules('id_sekolah', 'id_sekolah', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Sekolah.php */
/* Location: ./application/controllers/Sekolah.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-05-11 23:41:36 */
/* http://harviacode.com */