<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mahasiswa_model extends CI_Model
{

    public $table = 'tbl_mahasiswa';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,nim,nama,jk,fakultas,prodi,nama_sekolah,ta');
        $this->datatables->from('tbl_mahasiswa');
        //add this line for join
        $this->datatables->join('tbl_fakultas', 'tbl_mahasiswa.id_fakultas = tbl_fakultas.id_fakultas');
        $this->datatables->join('tbl_prodi', 'tbl_mahasiswa.id_prodi = tbl_prodi.id_prodi');
        $this->datatables->join('tbl_sekolah', 'tbl_mahasiswa.id_sekolah = tbl_sekolah.id_sekolah');
        $this->datatables->add_column('action', anchor('mahasiswa/read/$1','Read', array('class'=>'btn btn-primary'))." | ".anchor('mahasiswa/update/$1','Update', array('class'=>'btn btn-info'))." | ".anchor('mahasiswa/delete/$1','Delete',array('class'=>'btn btn-danger','onclick'=>"alert('yakin ingin menghapus ?')")), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('id,nim,nama,jk,tbl_mahasiswa.id_fakultas,fakultas,tbl_mahasiswa.id_prodi,prodi,tbl_mahasiswa.id_sekolah, nama_sekolah, ta');
        $this->db->where($this->id, $id);
        $this->db->from('tbl_mahasiswa');
        $this->db->join('tbl_fakultas', 'tbl_mahasiswa.id_fakultas = tbl_fakultas.id_fakultas');
        $this->db->join('tbl_prodi', 'tbl_mahasiswa.id_prodi = tbl_prodi.id_prodi');
        $this->db->join('tbl_sekolah', 'tbl_mahasiswa.id_sekolah = tbl_sekolah.id_sekolah');
        return $this->db->get()->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nim', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('jk', $q);
	$this->db->or_like('id_fakultas', $q);
	$this->db->or_like('id_prodi', $q);
    $this->db->or_like('id_sekolah', $q);
    $this->db->or_like('ta', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nim', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('jk', $q);
	$this->db->or_like('id_fakultas', $q);
	$this->db->or_like('id_prodi', $q);
    $this->db->or_like('id_sekolah', $q);
    $this->db->or_like('ta', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Mahasiswa_model.php */
/* Location: ./application/models/Mahasiswa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-09 01:00:06 */
/* http://harviacode.com */