<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sekolah_model extends CI_Model
{

    public $table = 'tbl_sekolah';
    public $id = 'id_sekolah';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_sekolah,nama_sekolah');
        $this->datatables->from('tbl_sekolah');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_sekolah.field = table2.field');
        $this->datatables->add_column('action', anchor('sekolah#update$1','Update', array(
            'class'=>'btn btn-info btn-xs',
            'data-toggle'=>'modal'))." ".anchor('sekolah#delete$1','Delete',array(
                'class'=>'btn btn-danger btn-xs',
                'data-toggle'=>'modal')), 'id_sekolah');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_sekolah', $q);
	$this->db->or_like('nama_sekolah', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_sekolah', $q);
	$this->db->or_like('nama_sekolah', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Sekolah_model.php */
/* Location: ./application/models/Sekolah_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-05-11 23:41:36 */
/* http://harviacode.com */